# Do not edit this file.

source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'

gem "sinatra-activerecord", :git => "https://github.com/janko-m/sinatra-activerecord.git"
gem "pg"

gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'

gem "rake"